INSERT INTO gics VALUES (10, 1010, 'Energy', 1, 'Energy');
INSERT INTO gics VALUES (15, 1510, 'Materials', 2, 'Materials');
INSERT INTO gics VALUES (20, 2010, 'Industrials', 3, 'Capital Goods');
INSERT INTO gics VALUES (20, 2020, 'Industrials', 3, 'Commercial & Professional Services');
INSERT INTO gics VALUES (20, 2030, 'Industrials', 3, 'Transportation');
INSERT INTO gics VALUES (25, 2510, 'Consumer Discretionary', 4, 'Automobiles & Components');
INSERT INTO gics VALUES (25, 2520, 'Consumer Discretionary', 4, 'Consumer Durables & Apparel');
INSERT INTO gics VALUES (25, 2530, 'Consumer Discretionary', 4, 'Customer Services');
INSERT INTO gics VALUES (25, 2550, 'Consumer Discretionary', 4, 'Retailing');
INSERT INTO gics VALUES (30, 3010, 'Comsumer Stables', 5, 'Food & Stables Retailing');
INSERT INTO gics VALUES (30, 3020, 'Comsumer Stables', 5, 'Food, Beverage & Tabacco');
INSERT INTO gics VALUES (30, 3030, 'Comsumer Stables', 5, 'Households & Personal Products');
INSERT INTO gics VALUES (35, 3510, 'Health Care', 6, 'Health Care Equipment & Services');
INSERT INTO gics VALUES (35, 3520, 'Health Care', 6, 'Pharmaceuticals, Biotechnology & Life Sciences ');
INSERT INTO gics VALUES (40, 4010, 'Financials', 7, 'Banks');
INSERT INTO gics VALUES (40, 4020, 'Financials', 7, 'Diversified Financials');
INSERT INTO gics VALUES (40, 4030, 'Financials', 7, 'Insurance');
INSERT INTO gics VALUES (45, 4510, 'Information Technology', 8, 'Software & Services');
INSERT INTO gics VALUES (45, 4520, 'Information Technology', 8, 'Technology Hardware & Equipment');
INSERT INTO gics VALUES (45, 4530, 'Information Technology', 8, 'Semiconductors & Semiconductor Equipment');
INSERT INTO gics VALUES (50, 5010, 'Communication Services', 9 , 'Communication Services');
INSERT INTO gics VALUES (50, 5020, 'Communication Services', 9 , 'Media & Entertainment');
INSERT INTO gics VALUES (55, 5510, 'Utilities', 10, 'Utilities');
INSERT INTO gics VALUES (60, 6010, 'Real Estate', 11, 'Real Estate');

commit;

INSERT INTO person VALUES (369, 'David', 'Pace', 'dpace12@gmail.com', 'M', '504-851-9685');
INSERT INTO person VALUES (258, 'Andy', 'Tran', 'atran78@gmail.com', 'M', '504-875-6163');
INSERT INTO person VALUES (147, 'Coral', 'Mckeon', 'cmckeon24@gmail.com', 'M', '504-981-3324');
INSERT INTO person VALUES (246, 'Amanda', 'Bui', 'abui445@gmail.com', 'F', '578-441-3365');

commit;
set define off
INSERT INTO company VALUES (0, 'Bay State', 'We have an exciting opportunity for an IT Specialist to join our team. Bay State brings together experienced IT professionals and the latest state-of-the-art...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=e0f433568fabe8e1&fccid=19aa0bbdd75afe67');
INSERT INTO company VALUES (1, 'AT&T', 'High School Diploma or General Equivalency Diploma (GED) Install, configure, service, repair, and maintain information technology systems in both a stand', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=af641a3c3dea6dc6&fccid=25b5166547bbf543');
INSERT INTO company VALUES (2, 'ACI Federal', 'Responsibilities: * Apply specialized knowledge in a single discipline such as assembly/integration, cross-discipline functions, data engineering, indust', 451020, 45102010, 'href=https://www.indeed.com/company/ACI-Federal/jobs/Information-Technology-Specialist-c5c93b734fc9673c?fccid=58476d2e8b9c7544');
INSERT INTO company VALUES (3, 'Hyatt', 'At Hyatt, we believe our guests select Hyatt because of our caring and attentive associates who are focused on providing efficient service and meaningful', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=cb8b9a04e68084af&fccid=b385273868d506a9');
INSERT INTO company VALUES (4, 'ACI Federal', 'One (1) year experience in IT required including at least one (1) year of customer service experience in IT....', 451020, 45102010, 'href=https://www.indeed.com/company/ACI-Federal/jobs/IT-Help-Desk-e1912fa78666532e?fccid=58476d2e8b9c7544');
INSERT INTO company VALUES (5, 'The Troubadour', 'Maintain IT audit compliance. Plan and budget all aspects of IT environment. Communicate and enforce adherence to all company IT security standards, practices...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=5a86c75262b3bdaf&fccid=0de594717975faf2');
INSERT INTO company VALUES (6, 'Sparkhound', 'An IT Help Desk / Service Desk - Tier I Support professional is responsible for supporting end-user devices. Three or more years of professional level technical...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=08b558b010eebe13&fccid=81965b70260b0455');
INSERT INTO company VALUES (7, 'Childrens Hospital', 'IT Director - Ancillary and Financial Systems. Prepares needed reports for all IT functions. Analyzes the operating and capital budgets and expenditures for...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=919461f5732612ea&fccid=ff8ce7baeed40030');
INSERT INTO company VALUES (8, 'Odyssey House Louisi', 'The PC Technician must have technical knowledge of Windows 7, 8/8.1, 10, OSX environments, network and PC operating systems, including printers and wireless...', 451020, 45102010, 'href=https://www.indeed.com/company/Odyssey-House-Louisiana');
INSERT INTO company VALUES (9, 'ACI Federal', 'IT Specialist JR. IT Systems (stand-alone and server environments). Install, Configure, Service, Repair and Maintain:....', 451020, 45102010, 'href=https://www.indeed.com/company/ACI-Federal/jobs/Information-Technology-Specialist-e1edc5da11ed7257?fccid=58476d2e8b9c7544');
INSERT INTO company VALUES (10, 'JK2S Solutions', 'We have Jr and Mid Positions available as well. Summary: This position?s primary role will be a Field Services Site Lead servicing a large scale Enterprise...', 451020, 45102010, 'href=https://www.indeed.com/company/JK2S/jobs/IT-Specialist-a98d514e0a89d602?fccid=2b0e2ec249ca6690');
INSERT INTO company VALUES (11, 'Destination Hotels & Resorts', 'Maintain IT audit compliance. Plan and budget all aspects of IT environment. Communicate and enforce adherence to all company IT security standards, practices...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=f9c4d675beee03de&fccid=e2dea33ac04eacd7');
INSERT INTO company VALUES (12, 'Fresenius Medical Care', 'Educate users on FMCNA and FMS IT policies and procedures as necessary. Responsible for providing Tier II computer desktop support to field locations in...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=a67a6895f6024c79&fccid=8de1633f2f8eae1d');
INSERT INTO company VALUES (13, 'CGI', 'The Service Desk Tier 2 technician is a skilled desktop support analyst that is the second layer of technical support and will go desk side as part of the...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=d6a2b63918c2f67a&fccid=d2841a5c0380b93d');
INSERT INTO company VALUES (14, 'Childrens Hospital', 'Extensive experience in repair of Desktop communications. The Network Technician?s role is to support the stable operation of the in-house communications...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=63fa7c1ddbbe629e&fccid=ff8ce7baeed40030');
INSERT INTO company VALUES (15, 'Epsilon Inc.', 'IT Specialist Junior. The IT Specialist Junior will, under immediate supervision, install, configure, service, repair, and maintain information technology...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=a414d2e6fdba1a4a&fccid=765e0365309ddf72');
INSERT INTO company VALUES (16, 'Network Runners', 'Is a Information Technology Solutions Company - providing innovative IT solutions and organizational support within the DOD and the Civil sector....', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=2932fd8cd8f3e5d0&fccid=957fdc33884615ec');
INSERT INTO company VALUES (17, 'Childrens Hospital', 'Works with internal IT teams on technical troubleshooting, integration, reporting and training. Help Desk support as needed....', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=1ba74ed0685baaea&fccid=ff8ce7baeed40030');
INSERT INTO company VALUES (18, 'First NBC Bank', 'Must have at least 7 years of information security, IT audit, or related experience. Must have knowledge of information systems and equipment, including, but...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=0667097456bbbb89&fccid=4cd44f8ed180811d');
INSERT INTO company VALUES (19, 'CACI', 'Help Desk mid provide support to users in resolving problems using help desk center tools. The RESPONSIBILITIES of the help desk mid may also include support in...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=facbfcd6eae2116d&fccid=290a4498a64fc044');
INSERT INTO company VALUES (20, 'Best Bu', 'Surrounded by the latest and greatest technology, a team of amazing coworkers and a work environment where anything is possible, you?ll find it easy to be your...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=a640d8e4b8d90b37&fccid=027d7cca25a5d14f');
INSERT INTO company VALUES (21, 'Childrens Hospital', 'IT Ancillary Applications Manager. IT communications, scheduling and decision making. The IT Ancillary Applications Manager works under the guidance of the IT...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=bc07c8c19c9bc594&fccid=ff8ce7baeed40030');
INSERT INTO company VALUES (22, 'Terrebonne General Medical Center', 'Under the general direction of the Information Technology Director and the Information Systems Manager, the Computer Systems Analyst provides technical', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=c0f455dfbbec71b7&fccid=b3eb08a7b54e330');
INSERT INTO company VALUES (23, 'Childrens Hospital', 'Healthcare IT project management experience preferred. LCMC Health is a Louisiana-based, not-for-profit healthcare system serving the needs of the people of...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=2202ec8834c37d5f&fccid=ff8ce7baeed40030');
INSERT INTO company VALUES (24, 'Tulane Universit', 'The Head of Library Information Technology is an innovative and imaginative professional overseeing a talented staff of research library...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=b5bac8d5b2fe0ad9&fccid=32f1f726276ba707');
INSERT INTO company VALUES (25, 'General Electri', 'Review end-to-end customer support processes to proactively identify gaps and prioritize/execute IT process improvements that increase customer satisfaction and...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=72335b196af723f7&fccid=c5c99ec01e2125aa');
INSERT INTO company VALUES (26, 'Ultimate Technical Solutions', 'Consulting company searching for the right candidate to join our team as an IT Help Desk Technician. UTSI is a premier I.T....', 451020, 45102010, 'href=https://www.indeed.com/company/Ultimate-Technical-Solution');
INSERT INTO company VALUES (27, 'Dell', 'Engage customer contacts at both a strategic, business focused and tactical, IT technology level. Assess the customer?s IT organization?s ability to respond to...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=8008ed3ac9a4b99c&fccid=0918a251e6902f97');
INSERT INTO company VALUES (28, 'Bay State', 'We have an exciting opportunity for a Junior IT Specialist to join our team. Bay State brings together experienced IT professionals and the latest state-of-the...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=ceef02536e51a437&fccid=19aa0bbdd75afe67');
INSERT INTO company VALUES (29, 'General Dynamics Information Technolog', 'Microsoft Certified IT Professional (MCITP):. Installing, configuring and maintaining desktop and laptop PCs and peripherals, such as printers....', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=84f39a6d77b6d4c7&fccid=11caadcdc98800d4');
INSERT INTO company VALUES (30, 'Kofax', 'The Technical Support Engineer is responsible for providing business critical technical support to highly skilled customer and partner IT and functional staff,...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=b5fe46f16f49f138&fccid=733ea912d58257f6');
INSERT INTO company VALUES (31, 'Gilsbar Holdings', 'The Help Desk plays a critical role in the operation of the Technology Department. Perform hands on fixes at the desktop level, including installing and...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=32633cdd1bbc0f8d&fccid=591edce286e3ff98');
INSERT INTO company VALUES (32, 'Terrebonne General Medical Center', 'Technical Manager, the Help Desk Analyst is responsible for the user support of computer applications and hardware. Under the general direction of the I.T....', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=067a9e422f810299&fccid=b3eb08a7b54e330');
INSERT INTO company VALUES (33, 'AT&T', 'High school Diploma or General Equivalency Diploma (GED) 2-4 years experience Under immediate supervision, responsible for all aspects of Information Syste', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=649ed703864958ca&fccid=25b5166547bbf543');
INSERT INTO company VALUES (34, 'Gilsbar', 'The Help Desk plays a critical role in the operation of the Technology Department. Perform hands on fixes at the desktop level, including installing and...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=079874832df2424d&fccid=79f204bea5e3ca6a');
INSERT INTO company VALUES (35, 'Bay State', 'Bay State brings together experienced IT professionals and the latest state-of-the-art technology tools, practices, and products to support projects and task...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=18e89539a950f845&fccid=19aa0bbdd75afe67');
INSERT INTO company VALUES (36, 'MECO (Mechanical Equipment Company Inc)', 'Additional responsibilities will include telephone lines, and teleconference support, responding to Help Desk issues, and conducting user training....', 451020, 45102010, 'href=https://www.indeed.com/company/MECO-(Mechanical-Equipment-Company-Inc)/jobs/PC-Technician-5dbe78cd759f9041?fccid=cefe145147cc4f55');
INSERT INTO company VALUES (37, 'JK2S Solutions', 'IT:. Under broad direction, operate and manage all aspects of Information Systems (IS), data availability, integrity, authentication, confidentiality, and non...', 451020, 45102010, 'href=https://www.indeed.com/company/JK2S/jobs/Cyber-Security-Specialist-8d7b858e774f5a81?fccid=2b0e2ec249ca6690');
INSERT INTO company VALUES (38, 'NRLC', 'NRLC is looking for an IT Consultant to assist in managing an established shared network with 10-15 computers....', 451020, 45102010, 'href=https://www.indeed.com/company/NRLC/jobs/IT-Consultant-c8e2c5238e583682?fccid=b1a5eca9eec687bd');
INSERT INTO company VALUES (39, 'tecinf', '> Proficiency in CMMI/SEI IT project management processes. Need a Applications Project manager....', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=12667e1eec8f6880&fccid=e36b62be8424611');
INSERT INTO company VALUES (40, 'XG Securit', 'A degree is not required for this job but it would be a plus. Responsibilities of Job....', 451020, 45102010, 'href=https://www.indeed.com/company/XG-Security/jobs/Network-Technician-66d4809724f46180?fccid=e11bfb886fc2ed49');
INSERT INTO company VALUES (41, 'Microsoft', 'The TAM must be a change agent by articulating the case for change and helping our customers Evolve their IT Maturity, drive productive use of Microsoft...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=1dfac62a08dcbf98&fccid=734cb5a01ee60f80');
INSERT INTO company VALUES (42, 'SpikeIT Global Solutions', 'Performing evaluation tasks on clients products and their IT environment. Under minimal supervision, involved in assessing complex IT infrastructures, systems,...', 451020, 45102010, 'href=https://www.indeed.com/company/SpikeIT-Global-Solutions/jobs/Cyber-Security-Analyst-0ba17389d1872fd7?fccid=f20f77a920649633');
INSERT INTO company VALUES (43, 'Volunteers of America Greater New Orleans', 'It is not to be construed as an exhaustive statement of duties, responsibilities or requirements. This position is responsible for overall management of housing...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=17d7017196a0b413&fccid=9cabce648c17e480');
INSERT INTO company VALUES (44, 'Louisiana State Government', 'It is a requirement that all Revenue employees must adhere to all tax laws of the State of Louisiana. If you do not have a score prior to applying to this...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=37da381b0797ba14&fccid=e0f35a124e6f113c');
INSERT INTO company VALUES (45, 'Best Bu', 'Does the thought of solving solutions for thousands of clients from your own desk and in their home sound like the best job ever?...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=b6abec5cfefd56d2&fccid=027d7cca25a5d14f');
INSERT INTO company VALUES (46, 'Knight Point Systems', 'Our staff maintain expertise spanning a wide spectrum of IT management, technology, and service solutions. Repeatedly recognized as an elite public sector IT...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=fdbede9aee82d101&fccid=c0309bed6539b87');
INSERT INTO company VALUES (47, 'Volunteers of America - New Orleans', 'It is not to be construed as an exhaustive statement of duties, responsibilities or requirements. This position is responsible for overall management of housing...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=cac7b17a7a8184a2&fccid=2945920d6a3cdd92');
INSERT INTO company VALUES (48, 'Enterg', 'Bachelor?s Degree Engineering Discipline or Experience Equivalent, EIT helpful - desired as relevant, IT or Engineering experience (will review IT Degrees)....', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=c68c2a08ba449c0f&fccid=4ba02d8aeaa3e74a');
INSERT INTO company VALUES (49, 'CapinCrouse LLP', 'Performs general information systems control reviews for simple to complex IT environments. CapinCrouse is looking for an Information Systems Auditor to be...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=ad086c2eba85d17a&fccid=8eba5bacc3d96bf6');
INSERT INTO company VALUES (50, 'Capriccio Software', 'We provide professional services in the classified IT arena as well as Business Intelligence and Microsoft .Net development services for public and private...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=bcaa471f23723e5d&fccid=504120812bd53c30');
INSERT INTO company VALUES (51, 'Hewlett Packard Enterprise', 'We are currently looking for an Help Desk Specialist to work in New Orleans, LA. Hewlett Packard Enterprise is a leading global technology services provider...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=8c911242b0c0bce9&fccid=216eb700022de6f6');
INSERT INTO company VALUES (52, 'Capriccio Software', 'We provide professional services in the classified IT arena as well as Business Intelligence and Microsoft .Net development services for public and private...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=0549029822cdca19&fccid=504120812bd53c30');
INSERT INTO company VALUES (53, 'Enterg', 'Bachelor?s Degree Engineering or Discipline or experience equivalent thereof, PD Desired, Advanced Engineering Degree helpful ? desired as relevant, IT or...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=551045e6028cba4e&fccid=4ba02d8aeaa3e74a');
INSERT INTO company VALUES (54, 'Ochsner Health Syste', 'As a 473-bed acute care hospital, it offers the opportunity to learn and provide patient care at a Magnet facility with three Centers of Excellence, all the...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=9f933808df1a76ff&fccid=ef34ff29d760a6f2');
INSERT INTO company VALUES (55, 'Deloitte', 'Providing a full range of industry leading services,including digital, systems integration and resource planning, we enable clientsto fine tune Application...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=92e081dd3d0651e2&fccid=9e215d88a6b33622');
INSERT INTO company VALUES (56, 'K2 Realt', 'We are the nation?s oldest and largest woman-owned IT Company. Providing remote Help Desk Support to our customer?s and field technicians....', 451020, 45102010, 'href=https://www.indeed.com/company/K2-realty/jobs/Technical-Support-55a188f4e547ba41?fccid=a8698a8ab9b0280c');
INSERT INTO company VALUES (57, 'Bay State', 'Bay State brings together experienced IT professionals and the latest state-of-the-art technology tools, practices, and products to support projects and task...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=73884389990f4426&fccid=19aa0bbdd75afe67');
INSERT INTO company VALUES (58, 'PSI Pax', 'PSI Pa x is currently recruiting for a n Enterprise IT Service Desk Specialist to sup port our government customer in New Orleans, LA ....', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=4328815d64741951&fccid=758bc63e5b967bdf');
INSERT INTO company VALUES (59, 'Anntoine Marketing and Desig', 'You will bridge the gap between graphical design and technical implementation, taking an active role on both sides and defining how the application looks as...', 451020, 45102010, 'href=https://www.indeed.com/company/Anntoine-Marketing-and-Design/jobs/Front-End-Web-Developer-30454b34f112d0e6?fccid=43d9c59f8bc9a58');
INSERT INTO company VALUES (60, 'Network Logi', 'Extensive experience trouble-shooting various Desktop issues. Network Logic, LLC located in Mandeville, Louisiana is seeking a full-time Network Technician with...', 451020, 45102010, 'href=https://www.indeed.com/company/Network-Logic');
INSERT INTO company VALUES (61, 'Bellwether Technolog', 'Progressive New Orleans based IT firm needs your skills. The systems engineer should already be a Microsoft Certified IT Professional and should continue to...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=0070c89b851f433b&fccid=9246a04bc0770376');
INSERT INTO company VALUES (62, 'MILVETS Systems Technolog', 'IT Specialist Jr. All candidates are required to pass a drug screening, criminal history check, and credit check PRIOR TO BEGINNING WORK. $11.57/hr....', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=98cc3c4cb60f0c37&fccid=bc61725f7ac26e7');
INSERT INTO company VALUES (63, 'Hewlett Packard Enterprise', 'We are currently looking for an Desktop Support Specialist to work in New Orleans, LA. Hewlett Packard Enterprise is a leading global technology services...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=3aeb2a5601d25a7f&fccid=216eb700022de6f6');
INSERT INTO company VALUES (64, 'Catapult Consultants', 'This position works as an integral member of a multidisciplinary team for a federal government contract to perform investigations to identify fraud, waste and', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=a8905826118cc538&fccid=2ef1c0aa55f82227');
INSERT INTO company VALUES (65, 'CSRA', 'CSRA plays a key role in the Departments IT integration strategy through its Data Center-1 program. Follows developed operating procedures and maintains record...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=181c0ff969418c22&fccid=0e18721ba57279e5');
INSERT INTO company VALUES (66, 'Pan-American Life Insurance Grou', 'The IT Software Developer is a member of an information technology team responsible for delivering new system functionality and supporting existing systems in...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=d127edaf56c77b1f&fccid=44a60fd5f29788e0');
INSERT INTO company VALUES (67, 'Aventure Technologies', 'Work closely with various technology support teams as well as with vendor technical support to ensure robust operational performance of Data Center networks,...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=18270403849b0428&fccid=265aa8abb6daba68');
INSERT INTO company VALUES (68, 'In-Telecom Consulting', 'Help Desk Technician*. In-Telecom Consulting is searching for a full time experienced Programming Technician....', 451020, 45102010, 'href=https://www.indeed.com/company/In--Telecom-Consulting/jobs/Help-Desk-Technician-6a74f1833174041c?fccid=eb755b9dde89fd1a');
INSERT INTO company VALUES (69, 'Abacus Technology Corporati', '3-5 years? experience in an IT service desk environment. Experience managing a tiered help desk providing enterprise level IT support....', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=8e7a6d1c5b0523dd&fccid=9b23f360c9f83ff0');
INSERT INTO company VALUES (70, 'Tulane Universit', 'It is comprised of over 30 different organizations seeking to address youth disconnection. The....', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=3177b752317c0da1&fccid=32f1f726276ba707');
INSERT INTO company VALUES (71, 'Creole Gardens Guesthouse', 'Help us keep it funky! Boutique Bed and Breakfast in the Lower Garden District searching for part time/full time (30+hours a week) Front Office Manager....', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=c8b78d1d3699e6db&fccid=259c1488e8517c41');
INSERT INTO company VALUES (72, 'Whetstone Educati', 'The platform allows school leaders to capture, organize, analyze, and share classroom observation data in an intuitive interface, making it easy to identify...', 451020, 45102010, 'href=https://www.indeed.com/company/Whetstone-Education/jobs/Software-Developer-74a1f84251acf9e9?fccid=7506d823742f237a');
INSERT INTO company VALUES (73, 'H2 Performance Consulting', 'Designing databases and creating tables, indexes, relationships, triggers, and stored procedures required to store all data and communicate it to the front-end...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=3c7ca62ea5c5d6c9&fccid=e26388c1e2a22dd7');
INSERT INTO company VALUES (74, 'Hewlett Packard Enterprise', 'Hewlett Packard Enterprise is a leading global technology services provider delivering business solutions to its clients. The HPE Enterprise Services delive', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=960837536cb6e36a&fccid=216eb700022de6f6');
INSERT INTO company VALUES (75, 'Laitram LLC', 'Laitram?s Information Technology Services Department has an opening for an IT Security Analyst, reporting to the IT Infrastructure Manager....', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=405a715ee81f5b02&fccid=06c0065578ad0db6');
INSERT INTO company VALUES (76, 'CSRA', 'IT Project Coordinator for DHS Datacenter SRF 2428 Requisition ID:. CSRA plays an integral role in the DHS IT integration strategy....', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=0782f9a10bf43dbf&fccid=0e18721ba57279e5');
INSERT INTO company VALUES (77, 'Booz Allen Hamilt', 'Job Number: R0002125 Booz Allen Hamilton has been at the forefront of strategy and technology for more than 100 years Today, the firm provides management and', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=49ce91b73e6da01a&fccid=4e041af1d0af1bc8');
INSERT INTO company VALUES (78, 'Louisiana State Government', 'If you are unable to apply online, you may fax your Civil Service application to 225-219-1041 or you may mail it to Staffing Division, Department of State Civil...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=c9dfbe14bf7cfb1d&fccid=e0f35a124e6f113c');
INSERT INTO company VALUES (79, 'La Health Solutions', 'For you, entering the right things into the correct places is childs play, but you love it. Do you love numbers?...', 451020, 45102010, 'href=https://www.indeed.com/company/La-Health-Solutions/jobs/Medical-Data-Entry-Genius-0425332037aec768?fccid=55b611e25019dd77');
INSERT INTO company VALUES (80, 'Best Bu', 'Consistently deliver on the promise of ?Do it right, do it swiftly, and keep the customer informed.?. Does the thought of installing an LCD in an SUV, and...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=e6639137991efe82&fccid=027d7cca25a5d14f');
INSERT INTO company VALUES (81, 'Hornbeck Offshore', 'The IT Help Desk / Field Technician is responsible for supporting various hardware, software and communication systems onboard the vessels and facilities that...', 451020, 45102010, 'href=https://www.indeed.com/company/Hornbeck-Offshore/jobs/IT-Help-Desk-b457e80657cfecc2?fccid=270ec55cf0d510e1');
INSERT INTO company VALUES (82, 'Tulane Universit', 'The university is located in beautiful uptown New Orleans where it borders the St. Proficiency with standard computer hardware and desktop applications,...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=f547b480f9c3bc73&fccid=32f1f726276ba707');
INSERT INTO company VALUES (83, 'Childrens Hospital', 'IT Director ? Revenue Cycle Applications. Prepares weekly, monthly, quarterly reports for all IT functions. IT experience in healthcare revenue cycle systems,...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=aa71cb00af4367b8&fccid=ff8ce7baeed40030');
INSERT INTO company VALUES (84, 'General Dynamics Information Technolog', 'General Dynamics IT has an immediate opening for an IT Systems Architect along the Gulf Coast in New Orleans;...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=fa563b708266ad6b&fccid=11caadcdc98800d4');
INSERT INTO company VALUES (85, 'zlie', 'It solves a headache. And ultimately, it shines a light on a very unjust and messy process, making it more fair and transparent for all....', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=eea7d6bb82bdda80&fccid=bac8e1cdec7d5d6c');
INSERT INTO company VALUES (86, 'Grand Family Dentistr', 'It means being a mentor, being a friend, and being part of a change that starts with each patient. Here at Grand Family Dentistry, our teams don?t just shape...', 451020, 45102010, 'href=https://www.indeed.com/company/Grand-Family-Dentistry/jobs/Office-Administrator-4dac0b089960324f?fccid=5e5fc9c2845d5f54');
INSERT INTO company VALUES (87, 'CSRA', 'CSC plays a key role in the Departments IT integration strategy. Deputy Program Manager w/Data Center Exp (SRF 2552) Requisition ID:....', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=e1a18bdad878d6d7&fccid=0e18721ba57279e5');
INSERT INTO company VALUES (88, 'Louisiana State Government', 'If you do not have a score prior to applying to this posting, it may result in your application not being considered....', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=f640a5fc8fcf62c6&fccid=e0f35a124e6f113c');
INSERT INTO company VALUES (89, 'Capriccio Software', 'IT Specialist ? Junior. The selected qualified candidate under general supervision will be responsible for providing IT services in connection with the Next...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=077a6d1ee52e1c5f&fccid=504120812bd53c30');
INSERT INTO company VALUES (90, 'Ernest N. Morial Convention Center', 'The Network Engineer is a well-rounded individual with experience working in mid to large size environments. A diverse technical skill set is required along', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=7a0074fbf25a929b&fccid=ada99f53cdd1f9cd');
INSERT INTO company VALUES (91, 'AT&T', 'Our employees say it best! Don?t take our word for it. What?s it like to join our team? Innovation starts in the hands of our customers, and our technicians...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=746a8f2d7ecf095d&fccid=25b5166547bbf543');
INSERT INTO company VALUES (92, 'Pan-American Life Insurance Grou', 'Minimum 4 years of information security, IT or risk management experience. The primary responsibility of this position is for implementing information security...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=f520fa5c0599ba3c&fccid=44a60fd5f29788e0');
INSERT INTO company VALUES (93, 'Bay State', 'One (1) year experience in IT required including at least one (1) year of customer service experience in IT....', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=14884f9ee58e55ca&fccid=19aa0bbdd75afe67');
INSERT INTO company VALUES (94, 'Capriccio Software', 'We provide professional services in the classified IT arena as well as Business Intelligence and Microsoft .Net development services for public and private...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=20d62d84011f4fc1&fccid=504120812bd53c30');
INSERT INTO company VALUES (95, 'The Lynd C', 'It does notprescribe or restrict the tasks that may be assigned, since all positions aresubject to change....', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=c215dae41f5c3204&fccid=a6273440d811796a');
INSERT INTO company VALUES (96, 'Capriccio Software', '1 year customer service experience in IT. Enterprise Service Desk Specialist - Mid. 1 year experience in Information Technology required including at least 1...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=a24253b32f323518&fccid=504120812bd53c30');
INSERT INTO company VALUES (97, 'General Electri', 'Bachelors Degree in ?STEM? Majors (Science, Technology, Engineering and Math) OR Completion of a code development pair-programming, bootcamp-style, or...', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=5377ff5d86d6d202&fccid=c5c99ec01e2125aa');
INSERT INTO company VALUES (98, 'CGI', 'Founded in 1976, CGI is a leading IT and business process services firm committed to helping clients succeed....', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=5c3d0fced8181f57&fccid=d2841a5c0380b93d');
INSERT INTO company VALUES (99, 'PosiGe', 'The IT Manager is responsible for developing and maintaining a good IT environment. High Degree of ownership in all matters within the IT infrastructure....', 451020, 45102010, 'href=https://www.indeed.com/rc/clk?jk=d4fdb9499f53ddc4&fccid=a19e8da745403832');
set define on
commit;

INSERT INTO address VALUES ();
INSERT INTO address VALUES ();
INSERT INTO address VALUES ();
INSERT INTO address VALUES ();

commit;

INSERT INTO position VALUES ();
INSERT INTO position VALUES ();
INSERT INTO position VALUES ();
INSERT INTO position VALUES ();

commit;

INSERT INTO payrate VALUES ();
INSERT INTO payrate VALUES ();
INSERT INTO payrate VALUES ();
INSERT INTO payrate VALUES ();

commit;

INSERT INTO job VALUES ();
INSERT INTO job VALUES ();
INSERT INTO job VALUES ();
INSERT INTO job VALUES ();

commit;

INSERT INTO skill VALUES (0, '.NET Programming', 'NULL', '0');
INSERT INTO skill VALUES (1, 'Ab Initio', 'NULL', '0');
INSERT INTO skill VALUES (2, 'Accounting Software', 'NULL', '0');
INSERT INTO skill VALUES (3, 'Activex Data Object (ADO)', 'NULL', '0');
INSERT INTO skill VALUES (4, 'Adobe Acrobat', 'NULL', '0');
INSERT INTO skill VALUES (5, 'Adobe ColdFusion', 'NULL', '0');
INSERT INTO skill VALUES (6, 'Adobe Creative Suite', 'NULL', '0');
INSERT INTO skill VALUES (7, 'Adobe Dreamweaver', 'NULL', '0');
INSERT INTO skill VALUES (8, 'Adobe Flex', 'NULL', '0');
INSERT INTO skill VALUES (9, 'Adobe Illustrator', 'NULL', '0');
INSERT INTO skill VALUES (10, 'Adobe Indesign', 'NULL', '0');
INSERT INTO skill VALUES (11, 'Adobe Photoshop', 'NULL', '0');
INSERT INTO skill VALUES (12, 'ADP Payroll', 'NULL', '0');
INSERT INTO skill VALUES (13, 'AJAX', 'NULL', '0');
INSERT INTO skill VALUES (14, 'Amazon Web Services (AWS)', 'NULL', '0');
INSERT INTO skill VALUES (15, 'Android', 'NULL', '0');
INSERT INTO skill VALUES (16, 'Android Software Development Kit (SDK)', 'NULL', '0');
INSERT INTO skill VALUES (17, 'AngularJS', 'NULL', '0');
INSERT INTO skill VALUES (18, 'AngularJS', 'NULL', '0');
INSERT INTO skill VALUES (19, 'Apache CXF', 'NULL', '0');
INSERT INTO skill VALUES (20, 'Apache Hadoop', 'NULL', '0');
INSERT INTO skill VALUES (21, 'Apache Hive', 'NULL', '0');
INSERT INTO skill VALUES (22, 'Apache Subversion (SVN)', 'NULL', '0');
INSERT INTO skill VALUES (23, 'Apache Webserver', 'NULL', '0');
INSERT INTO skill VALUES (24, 'ArcGIS', 'NULL', '0');
INSERT INTO skill VALUES (25, 'AS/400', 'NULL', '0');
INSERT INTO skill VALUES (26, 'ASP', 'NULL', '0');
INSERT INTO skill VALUES (27, 'Atlassian JIRA', 'NULL', '0');
INSERT INTO skill VALUES (28, 'AutoCAD', 'NULL', '0');
INSERT INTO skill VALUES (29, 'Autodesk', 'NULL', '0');
INSERT INTO skill VALUES (30, 'Backbone.js', 'NULL', '0');
INSERT INTO skill VALUES (31, 'Bash', 'NULL', '0');
INSERT INTO skill VALUES (32, 'Bugzilla', 'NULL', '0');
INSERT INTO skill VALUES (33, 'BusinessObjects', 'NULL', '0');
INSERT INTO skill VALUES (34, 'C++', 'NULL', '0');
INSERT INTO skill VALUES (35, 'Cacti', 'NULL', '0');
INSERT INTO skill VALUES (36, 'CADD', 'NULL', '0');
INSERT INTO skill VALUES (37, 'Cassandra', 'NULL', '0');
INSERT INTO skill VALUES (38, 'Chef', 'NULL', '0');
INSERT INTO skill VALUES (39, 'Cisco Routers', 'NULL', '0');
INSERT INTO skill VALUES (40, 'Citrix', 'NULL', '0');
INSERT INTO skill VALUES (41, 'Civil 3D', 'NULL', '0');
INSERT INTO skill VALUES (42, 'COBOL', 'NULL', '0');
INSERT INTO skill VALUES (43, 'Cognos Impromptu', 'NULL', '0');
INSERT INTO skill VALUES (44, 'Computer Aided Drafting/Design (CAD)', 'NULL', '0');
INSERT INTO skill VALUES (45, 'Crystal Reports', 'NULL', '0');
INSERT INTO skill VALUES (46, 'CSS', 'NULL', '0');
INSERT INTO skill VALUES (47, 'Customer Information Control System (CICS)', 'NULL', '0');
INSERT INTO skill VALUES (48, 'Customer Relationship Management (CRM)', 'NULL', '0');
INSERT INTO skill VALUES (49, 'Data Visualization', 'NULL', '0');
INSERT INTO skill VALUES (50, 'Database Software', 'NULL', '0');
INSERT INTO skill VALUES (51, 'Datastage', 'NULL', '0');
INSERT INTO skill VALUES (52, 'Delphi', 'NULL', '0');
INSERT INTO skill VALUES (53, 'Design Software', 'NULL', '0');
INSERT INTO skill VALUES (54, 'Django', 'NULL', '0');
INSERT INTO skill VALUES (55, 'Dojo Toolkit', 'NULL', '0');
INSERT INTO skill VALUES (56, 'Drupal', 'NULL', '0');
INSERT INTO skill VALUES (57, 'Dynamic HTML', 'NULL', '0');
INSERT INTO skill VALUES (58, 'Eclipse', 'NULL', '0');
INSERT INTO skill VALUES (59, 'Electronic Data Interchange', 'NULL', '0');
INSERT INTO skill VALUES (60, 'Enterprise JAVA Beans', 'NULL', '0');
INSERT INTO skill VALUES (61, 'Enterprise Resource Planning (ERP)', 'NULL', '0');
INSERT INTO skill VALUES (62, 'Epic Systems', 'NULL', '0');
INSERT INTO skill VALUES (63, 'ERwin', 'NULL', '0');
INSERT INTO skill VALUES (64, 'Ext JS', 'NULL', '0');
INSERT INTO skill VALUES (65, 'Extensible Markup Language (XML)', 'NULL', '0');
INSERT INTO skill VALUES (66, 'Extensible Stylesheet Language XSL', 'NULL', '0');
INSERT INTO skill VALUES (67, 'Facebook', 'NULL', '0');
INSERT INTO skill VALUES (68, 'FileMaker Pro', 'NULL', '0');
INSERT INTO skill VALUES (69, 'Fortran', 'NULL', '0');
INSERT INTO skill VALUES (70, 'FoxPro', 'NULL', '0');
INSERT INTO skill VALUES (71, 'Geographic Information System (GIS)', 'NULL', '0');
INSERT INTO skill VALUES (72, 'Geopak', 'NULL', '0');
INSERT INTO skill VALUES (73, 'Git', 'NULL', '0');
INSERT INTO skill VALUES (74, 'Google AdWords', 'NULL', '0');
INSERT INTO skill VALUES (75, 'Google Analytics', 'NULL', '0');
INSERT INTO skill VALUES (76, 'Google Web Toolkit', 'NULL', '0');
INSERT INTO skill VALUES (77, 'Graphical User Interface (GUI)', 'NULL', '0');
INSERT INTO skill VALUES (78, 'Great Plains Accounting Software', 'NULL', '0');
INSERT INTO skill VALUES (79, 'Greenplum', 'NULL', '0');
INSERT INTO skill VALUES (80, 'Groupwise', 'NULL', '0');
INSERT INTO skill VALUES (81, 'HAZOP', 'NULL', '0');
INSERT INTO skill VALUES (82, 'HCPCS Coding', 'NULL', '0');
INSERT INTO skill VALUES (83, 'Heroku', 'NULL', '0');
INSERT INTO skill VALUES (84, 'Hibernate', 'NULL', '0');
INSERT INTO skill VALUES (85, 'HP-UX', 'NULL', '0');
INSERT INTO skill VALUES (86, 'HRMS', 'NULL', '0');
INSERT INTO skill VALUES (87, 'HTML5', 'NULL', '0');
INSERT INTO skill VALUES (88, 'Hyperion', 'NULL', '0');
INSERT INTO skill VALUES (89, 'HyperText Markup Language', 'NULL', '0');
INSERT INTO skill VALUES (90, 'Hypertext Preprocessor (PHP)', 'NULL', '0');
INSERT INTO skill VALUES (91, 'Hyper-V', 'NULL', '0');
INSERT INTO skill VALUES (92, 'IBM WEBSPHERE', 'NULL', '0');
INSERT INTO skill VALUES (93, 'ICD-10', 'NULL', '0');
INSERT INTO skill VALUES (94, 'ICD-9-CM Coding', 'NULL', '0');
INSERT INTO skill VALUES (95, 'Informatica', 'NULL', '0');
INSERT INTO skill VALUES (96, 'Inroads', 'NULL', '0');
INSERT INTO skill VALUES (97, 'Integrated Development Environment (IDE)', 'NULL', '0');
INSERT INTO skill VALUES (98, 'iPhone Software Development Kit (SDK)', 'NULL', '0');
INSERT INTO skill VALUES (99, 'ISO 9000', 'NULL', '0');
INSERT INTO skill VALUES (100, 'J2EE', 'NULL', '0');
INSERT INTO skill VALUES (101, 'JAVA', 'NULL', '0');
INSERT INTO skill VALUES (102, 'Java Applets', 'NULL', '0');
INSERT INTO skill VALUES (103, 'Java Message Service (JMS)', 'NULL', '0');
INSERT INTO skill VALUES (104, 'Java Naming and Directory Interface (JNDI)', 'NULL', '0');
INSERT INTO skill VALUES (105, 'Java Server Pages (JSP)', 'NULL', '0');
INSERT INTO skill VALUES (106, 'Java Servlets', 'NULL', '0');
INSERT INTO skill VALUES (107, 'JavaBeans', 'NULL', '0');
INSERT INTO skill VALUES (108, 'JavaScript', 'NULL', '0');
INSERT INTO skill VALUES (109, 'JavaServer Faces', 'NULL', '0');
INSERT INTO skill VALUES (110, 'JBoss', 'NULL', '0');
INSERT INTO skill VALUES (111, 'JD Edwards', 'NULL', '0');
INSERT INTO skill VALUES (112, 'JDBC', 'NULL', '0');
INSERT INTO skill VALUES (113, 'Jenkins', 'NULL', '0');
INSERT INTO skill VALUES (114, 'Job Control Language (JCL)', 'NULL', '0');
INSERT INTO skill VALUES (115, 'jQuery', 'NULL', '0');
INSERT INTO skill VALUES (116, 'JRUN', 'NULL', '0');
INSERT INTO skill VALUES (117, 'JSON', 'NULL', '0');
INSERT INTO skill VALUES (118, 'JUnit', 'NULL', '0');
INSERT INTO skill VALUES (119, 'Korn Shell (KSH)', 'NULL', '0');
INSERT INTO skill VALUES (120, 'LexisNexis', 'NULL', '0');
INSERT INTO skill VALUES (121, 'LinkedIn', 'NULL', '0');
INSERT INTO skill VALUES (122, 'LINUX', 'NULL', '0');
INSERT INTO skill VALUES (123, 'Load Runner', 'NULL', '0');
INSERT INTO skill VALUES (124, 'Log4J', 'NULL', '0');
INSERT INTO skill VALUES (125, 'Lotus Applications', 'NULL', '0');
INSERT INTO skill VALUES (126, 'Lotus Domino', 'NULL', '0');
INSERT INTO skill VALUES (127, 'Lotus Notes', 'NULL', '0');
INSERT INTO skill VALUES (128, 'MacIntosh OS', 'NULL', '0');
INSERT INTO skill VALUES (129, 'Macromedia Fireworks', 'NULL', '0');
INSERT INTO skill VALUES (130, 'Macros', 'NULL', '0');
INSERT INTO skill VALUES (131, 'MapReduce', 'NULL', '0');
INSERT INTO skill VALUES (132, 'MAS 200', 'NULL', '0');
INSERT INTO skill VALUES (133, 'MAS 90', 'NULL', '0');
INSERT INTO skill VALUES (134, 'MATLAB', 'NULL', '0');
INSERT INTO skill VALUES (135, 'Maven', 'NULL', '0');
INSERT INTO skill VALUES (136, 'McAfee', 'NULL', '0');
INSERT INTO skill VALUES (137, 'Meditech', 'NULL', '0');
INSERT INTO skill VALUES (138, 'Microsoft Access', 'NULL', '0');
INSERT INTO skill VALUES (139, 'Microsoft C', 'NULL', '0');
INSERT INTO skill VALUES (140, 'Microsoft C#', 'NULL', '0');
INSERT INTO skill VALUES (141, 'Microsoft CRM', 'NULL', '0');
INSERT INTO skill VALUES (142, 'Microsoft Dynamics', 'NULL', '0');
INSERT INTO skill VALUES (143, 'Microsoft Excel', 'NULL', '0');
INSERT INTO skill VALUES (144, 'Microsoft Exchange', 'NULL', '0');
INSERT INTO skill VALUES (145, 'Microsoft Office', 'NULL', '0');
INSERT INTO skill VALUES (146, 'Microsoft Operating Systems', 'NULL', '0');
INSERT INTO skill VALUES (147, 'Microsoft Outlook', 'NULL', '0');
INSERT INTO skill VALUES (148, 'Microsoft Powerpoint', 'NULL', '0');
INSERT INTO skill VALUES (149, 'Microsoft PowerShell', 'NULL', '0');
INSERT INTO skill VALUES (150, 'Microsoft Project', 'NULL', '0');
INSERT INTO skill VALUES (151, 'Microsoft Publisher', 'NULL', '0');
INSERT INTO skill VALUES (152, 'Microsoft Sharepoint', 'NULL', '0');
INSERT INTO skill VALUES (153, 'Microsoft SQL', 'NULL', '0');
INSERT INTO skill VALUES (154, 'Microsoft Sql Server Integration Services (SSIS)', 'NULL', '0');
INSERT INTO skill VALUES (155, 'Microsoft Visio', 'NULL', '0');
INSERT INTO skill VALUES (156, 'Microsoft Vista', 'NULL', '0');
INSERT INTO skill VALUES (157, 'Microsoft Windows', 'NULL', '0');
INSERT INTO skill VALUES (158, 'Microsoft Word', 'NULL', '0');
INSERT INTO skill VALUES (159, 'Microstation', 'NULL', '0');
INSERT INTO skill VALUES (160, 'Microstrategy', 'NULL', '0');
INSERT INTO skill VALUES (161, 'Middleware', 'NULL', '0');
INSERT INTO skill VALUES (162, 'Minitab', 'NULL', '0');
INSERT INTO skill VALUES (163, 'Mobile Application Design', 'NULL', '0');
INSERT INTO skill VALUES (164, 'Model-View-Controller (MVC)', 'NULL', '0');
INSERT INTO skill VALUES (165, 'MongoDB', 'NULL', '0');
INSERT INTO skill VALUES (166, 'MQSeries', 'NULL', '0');
INSERT INTO skill VALUES (167, 'MySQL', 'NULL', '0');
INSERT INTO skill VALUES (168, 'Nagios', 'NULL', '0');
INSERT INTO skill VALUES (169, 'Netcool', 'NULL', '0');
INSERT INTO skill VALUES (170, 'Node.js', 'NULL', '0');
INSERT INTO skill VALUES (171, 'NoSQL', 'NULL', '0');
INSERT INTO skill VALUES (172, 'Novell NetWare', 'NULL', '0');
INSERT INTO skill VALUES (173, 'Objective C', 'NULL', '0');
INSERT INTO skill VALUES (174, 'Object-Oriented Programming', 'NULL', '0');
INSERT INTO skill VALUES (175, 'Open Database Connectivity (ODBC)', 'NULL', '0');
INSERT INTO skill VALUES (176, 'Oracle', 'NULL', '0');
INSERT INTO skill VALUES (177, 'Oracle Business Intelligence Enterprise Edition (OBIEE)', 'NULL', '0');
INSERT INTO skill VALUES (178, 'Oracle PL/SQL', 'NULL', '0');
INSERT INTO skill VALUES (179, 'Palm OS', 'NULL', '0');
INSERT INTO skill VALUES (180, 'Peoplesoft', 'NULL', '0');
INSERT INTO skill VALUES (181, 'PeopleSoft Financials', 'NULL', '0');
INSERT INTO skill VALUES (182, 'PeopleSoft HRMS', 'NULL', '0');
INSERT INTO skill VALUES (183, 'Peopletools', 'NULL', '0');
INSERT INTO skill VALUES (184, 'Perforce', 'NULL', '0');
INSERT INTO skill VALUES (185, 'PERL', 'NULL', '0');
INSERT INTO skill VALUES (186, 'PIG', 'NULL', '0');
INSERT INTO skill VALUES (187, 'Platform as a Service (PaaS)', 'NULL', '0');
INSERT INTO skill VALUES (188, 'PostgreSQL', 'NULL', '0');
INSERT INTO skill VALUES (189, 'Primavera', 'NULL', '0');
INSERT INTO skill VALUES (190, 'Pro*C', 'NULL', '0');
INSERT INTO skill VALUES (191, 'Puppet', 'NULL', '0');
INSERT INTO skill VALUES (192, 'Python', 'NULL', '0');
INSERT INTO skill VALUES (193, 'Qlikview', 'NULL', '0');
INSERT INTO skill VALUES (194, 'Quick Test Professional (QTP)', 'NULL', '0');
INSERT INTO skill VALUES (195, 'Quickbooks', 'NULL', '0');
INSERT INTO skill VALUES (196, 'R', 'NULL', '0');
INSERT INTO skill VALUES (197, 'Raisers Edge', 'NULL', '0');
INSERT INTO skill VALUES (198, 'Rational Rose', 'NULL', '0');
INSERT INTO skill VALUES (199, 'Red Hat Linux', 'NULL', '0');
INSERT INTO skill VALUES (200, 'Relational DataBase Management System (RDBMS)', 'NULL', '0');
INSERT INTO skill VALUES (201, 'Revit', 'NULL', '0');
INSERT INTO skill VALUES (202, 'RIAK', 'NULL', '0');
INSERT INTO skill VALUES (203, 'Ruby', 'NULL', '0');
INSERT INTO skill VALUES (204, 'Ruby on Rails', 'NULL', '0');
INSERT INTO skill VALUES (205, 'Salesforce', 'NULL', '0');
INSERT INTO skill VALUES (206, 'SAP', 'NULL', '0');
INSERT INTO skill VALUES (207, 'Sap Basis', 'NULL', '0');
INSERT INTO skill VALUES (208, 'SAP HR', 'NULL', '0');
INSERT INTO skill VALUES (209, 'SAP Netweaver', 'NULL', '0');
INSERT INTO skill VALUES (210, 'SAS', 'NULL', '0');
INSERT INTO skill VALUES (211, 'Selenium', 'NULL', '0');
INSERT INTO skill VALUES (212, 'Service-Oriented Architecture (SOA)', 'NULL', '0');
INSERT INTO skill VALUES (213, 'Sharepoint Portal Server', 'NULL', '0');
INSERT INTO skill VALUES (214, 'Shell Scripting', 'NULL', '0');
INSERT INTO skill VALUES (215, 'SOAP', 'NULL', '0');
INSERT INTO skill VALUES (216, 'Social Media Platforms', 'NULL', '0');
INSERT INTO skill VALUES (217, 'Software as a Service (SaaS)', 'NULL', '0');
INSERT INTO skill VALUES (218, 'Solaris', 'NULL', '0');
INSERT INTO skill VALUES (219, 'SOLR', 'NULL', '0');
INSERT INTO skill VALUES (220, 'Splunk', 'NULL', '0');
INSERT INTO skill VALUES (221, 'Spring Framework', 'NULL', '0');
INSERT INTO skill VALUES (222, 'SPSS', 'NULL', '0');
INSERT INTO skill VALUES (223, 'SQL', 'NULL', '0');
INSERT INTO skill VALUES (224, 'SQL Server', 'NULL', '0');
INSERT INTO skill VALUES (225, 'SQL Server Analysis Services (SSAS)', 'NULL', '0');
INSERT INTO skill VALUES (226, 'SQL Server Reporting Services (SSRS)', 'NULL', '0');
INSERT INTO skill VALUES (227, 'SQL*Loader', 'NULL', '0');
INSERT INTO skill VALUES (228, 'SQLite', 'NULL', '0');
INSERT INTO skill VALUES (229, 'Sqoop', 'NULL', '0');
INSERT INTO skill VALUES (230, 'STATA', 'NULL', '0');
INSERT INTO skill VALUES (231, 'Structured Query Reporter (SQR)', 'NULL', '0');
INSERT INTO skill VALUES (232, 'Struts', 'NULL', '0');
INSERT INTO skill VALUES (233, 'Subversion', 'NULL', '0');
INSERT INTO skill VALUES (234, 'Swift', 'NULL', '0');
INSERT INTO skill VALUES (235, 'Sybase', 'NULL', '0');
INSERT INTO skill VALUES (236, 'Symantec Packages', 'NULL', '0');
INSERT INTO skill VALUES (237, 'Tableau', 'NULL', '0');
INSERT INTO skill VALUES (238, 'Teradata', 'NULL', '0');
INSERT INTO skill VALUES (239, 'Tivoli', 'NULL', '0');
INSERT INTO skill VALUES (240, 'Tomcat', 'NULL', '0');
INSERT INTO skill VALUES (241, 'Transact-SQL', 'NULL', '0');
INSERT INTO skill VALUES (242, 'Ubuntu', 'NULL', '0');
INSERT INTO skill VALUES (243, 'Unified Modeling Language (UML)', 'NULL', '0');
INSERT INTO skill VALUES (244, 'UNIX', 'NULL', '0');
INSERT INTO skill VALUES (245, 'UNIX Shell', 'NULL', '0');
INSERT INTO skill VALUES (246, 'Usability Testing', 'NULL', '0');
INSERT INTO skill VALUES (247, 'User Interface (UI) Design', 'NULL', '0');
INSERT INTO skill VALUES (248, 'VBScript', 'NULL', '0');
INSERT INTO skill VALUES (249, 'Veritas NetBackup', 'NULL', '0');
INSERT INTO skill VALUES (250, 'Virtual Private Networking (VPN)', 'NULL', '0');
INSERT INTO skill VALUES (251, 'Visual Basic', 'NULL', '0');
INSERT INTO skill VALUES (252, 'Visual Basic for Applications (VBA)', 'NULL', '0');
INSERT INTO skill VALUES (253, 'Visual Design', 'NULL', '0');
INSERT INTO skill VALUES (254, 'Visual Studio', 'NULL', '0');
INSERT INTO skill VALUES (255, 'VMware', 'NULL', '0');
INSERT INTO skill VALUES (256, 'VMware ESXi', 'NULL', '0');
INSERT INTO skill VALUES (257, 'Voice over IP (VoIP)', 'NULL', '0');
INSERT INTO skill VALUES (258, 'web authoring tools', 'NULL', '0');
INSERT INTO skill VALUES (259, 'WebLogic', 'NULL', '0');
INSERT INTO skill VALUES (260, 'Windows NT', 'NULL', '0');
INSERT INTO skill VALUES (261, 'Windows Server', 'NULL', '0');
INSERT INTO skill VALUES (262, 'Wireshark', 'NULL', '0');
INSERT INTO skill VALUES (263, 'Wonderware', 'NULL', '0');
INSERT INTO skill VALUES (264, 'Word Processing', 'NULL', '0');
INSERT INTO skill VALUES (265, 'WordPerfect', 'NULL', '0');
INSERT INTO skill VALUES (266, 'WordPress', 'NULL', '0');
INSERT INTO skill VALUES (267, 'XHTML', 'NULL', '0');
INSERT INTO skill VALUES (268, 'Yardi Software', 'NULL', '0');
INSERT INTO skill VALUES (269, 'Youtube', 'NULL', '0');

commit;

INSERT INTO requirement VALUES ();
INSERT INTO requirement VALUES ();
INSERT INTO requirement VALUES ();
INSERT INTO requirement VALUES ();

commit;

INSERT INTO course VALUES ();
INSERT INTO course VALUES ();
INSERT INTO course VALUES ();
INSERT INTO course VALUES ();

commit;

INSERT INTO section VALUES ();
INSERT INTO section VALUES ();
INSERT INTO section VALUES ();
INSERT INTO section VALUES ();

commit;

---------------------------------------------------------------------------------------------------------------------------------------

INSERT INTO store VALUES (1, '608 Joe Mama', 70072, '504-988-4742');
INSERT INTO store VALUES (2, '897 Maydu Street', 70078, '504-988-8975');
INSERT INTO store VALUES (3, '625 Lema Avenue', 70052, '504-988-6563');
INSERT INTO store VALUES (4, '879 Ligma Court', 70089, '504-988-3465');

commit;

INSERT INTO stocks VALUES (1,23);
INSERT INTO stocks VALUES (2,26);
INSERT INTO stocks VALUES (3,65);
INSERT INTO stocks VALUES (4,81);

commit;

INSERT INTO inventory VALUES (23, 'Milk', 'White', 30, 1, 15, 13, 10 );
INSERT INTO inventory VALUES (26, 'Egg', 'Brown Oval',50, 12, 10, 8, 4);
INSERT INTO inventory VALUES (65, 'Banana','Yellow', 20, 5, 7, 6, 8);
INSERT INTO inventory VALUES (81, 'Salmon', 'Orange', 34, 1, 20, 25, 15);

commit;

INSERT INTO sale VALUES (45, to_date('07/12/2010', 'dd/mm/yyyy'), 23, 30, 14,'Expire early', 10);
INSERT INTO sale VALUES (46, to_date('25/04/2020', 'dd/mm/yyyy'), 26, 50, 11,'Commonly in dozen', 4);
INSERT INTO sale VALUES (47, to_date('16/03/2021', 'dd/mm/yyyy'), 65, 20, 6,'Green is not spoil', 8);
INSERT INTO sale VALUES (48, to_date('30/10/2019', 'dd/mm/yyyy'), 81, 34, 21,'4 inches long', 15);

commit;

INSERT INTO purchaseaz VALUES (100, to_date('12/12/2010', 'dd/mm/yyyy'), 23, 1, 16, 'One that last longer');
INSERT INTO purchaseaz VALUES (101, to_date('30/04/2020', 'dd/mm/yyyy'), 26, 2, 13, 'Need 2 dozen');
INSERT INTO purchaseaz VALUES (102, to_date('23/03/2021', 'dd/mm/yyyy'), 65, 1, 8, 'Green mean it last longer');
INSERT INTO purchaseaz VALUES (103, to_date('03/11/2019', 'dd/mm/yyyy'), 81, 5, 23, 'Get the longest one');

commit;
----------------------------------------------------------------------------------------------------------------------------------------
INSERT INTO factory VALUES (50, 'Stellar', '548 Dweb Street', 77205,'504-987-8864', 'Carl');
INSERT INTO factory VALUES (51, 'Telsa', '21 Jump Street', 52003,'654-886-7913', 'Braken');
INSERT INTO factory VALUES (52, 'Nikola', '420 Beethoven Avenue', 70056, '231-504-5048', 'Niko');
INSERT INTO factory VALUES (53, 'Orbis', '62 Orcale Lane', 65002, '563-989-4223', 'Eden');

commit;

INSERT INTO searches VALUES (50,123);
INSERT INTO searches VALUES (51,156);
INSERT INTO searches VALUES (52,236);
INSERT INTO searches VALUES (53,300);

commit;

INSERT INTO material VALUES (123, 'Iron', 100, 5, 10);
INSERT INTO material VALUES (156, 'Copper', 30, 6, 12);
INSERT INTO material VALUES (236, 'Uranium', 25, 3, 25);
INSERT INTO material VALUES (300, 'Vibranium', 15, 1, 20;

commit;
 
INSERT INTO product VALUES (10, 'Fridge', 'Freeze food', 20, 1, 100);
INSERT INTO product VALUES (11, 'Wire', 'Electrical wiring', 100, 5, 25);
INSERT INTO product VALUES (12, 'Reactor', 'Alternative energy', 5, 1, 2000);
INSERT INTO product VALUES (13, 'Shield', 'Denfense and offense', 3, 1, 1500);

commit;

INSERT INTO contract VALUES (654, 456,to_date('12/08/2010', 'dd/mm/yyyy'),200,to_date('30/12/2010', 'dd/mm/yyyy'));
INSERT INTO contract VALUES (253, 352,to_date('11/12/2015', 'dd/mm/yyyy'),100,to_date('05/03/2016', 'dd/mm/yyyy'));
INSERT INTO contract VALUES (879, 421,to_date('05/26/2019', 'dd/mm/yyyy'),1800,to_date('01/01/2020', 'dd/mm/yyyy'));
INSERT INTO contract VALUES (666, 777,to_date('09/09/2021', 'dd/mm/yyyy'),1250,to_date('12/12/2021', 'dd/mm/yyyy'));

commit;

INSERT INTO lineitem VALUES (654, 10, 20);
INSERT INTO lineitem VALUES (253,11, 100);
INSERT INTO lineitem VALUES (879,12, 5);
INSERT INTO lineitem VALUES (666,13, 3);

commit;

INSERT INTO purhcase VALUES (101, 999, 90, to_date('12/12/2010', 'dd/mm/yyyy'), to_date('12/12/2010', 'dd/mm/yyyy'), 'Notw');
INSERT INTO purhcase VALUES (103, 111, 65, to_date('12/12/2010', 'dd/mm/yyyy'), to_date('12/12/2010', 'dd/mm/yyyy'), '');
INSERT INTO purhcase VALUES (105, 333, 33, to_date('12/12/2010', 'dd/mm/yyyy'), to_date('12/12/2010', 'dd/mm/yyyy'), '');
INSERT INTO purhcase VALUES (110, 555, 77, to_date('12/12/2010', 'dd/mm/yyyy'), to_date('12/12/2010', 'dd/mm/yyyy'), '');

commit;

INSERT INTO purhcaseline VALUES (101, 123, 100);
INSERT INTO purhcaseline VALUES (103, 156, 30);
INSERT INTO purhcaseline VALUES (105, 236, 25);
INSERT INTO purhcaseline VALUES (110, 300, 15);

commit;

INSERT INTO supplier VALUES (999, 'www.Buber.com', 'buber@gmail.com');
INSERT INTO supplier VALUES (111, 'www.Wubber.om', 'wubbersupport@yahoo.com');
INSERT INTO supplier VALUES (333, 'www.NASE.org', 'nasenotnasa@hotmail.com');
INSERT INTO supplier VALUES (555, 'www.Owo.net', 'uwuowo@gmail.com');

commit;

INSERT INTO customer VALUES (456, 'Marley', 'marley123@gmail.com');
INSERT INTO customer VALUES (352, 'Eldiana', 'eldia522@gmail.com');
INSERT INTO customer VALUES (421, 'Galio', 'galioLol@yahoo.com');
INSERT INTO customer VALUES (777, 'Jesus', 'itsjesus69@heaven.com');

commit;

INSERT INTO makes VALUES (50, 10, 20);
INSERT INTO makes VALUES (51, 11, 100);
INSERT INTO makes VALUES (52, 12, 5);
INSERT INTO makes VALUES (53, 13, 3);

commit;